### ISSUE TITLE
Feature Request: Ability to deploy the stack into a sub-compartment

### ISSUE THREAD

**Issue by kubemen** [oracle-devrel/terraform-oci-ocloud-landing-zone#9]
I would like to request the feature request to deploy the repository into a sub-directory to enable users to install the landing zone in parallel in two different sub-compartments.
this would help us in developing the code by multiply users at the same time in one tenancy

**Comment by torstenboettjer** [comment]
Please review code, all four compartments refer to a common parent now. Currently this parent is set in TF, we can consider to set it in the schema file.
